return {
    defaults={
        ['bank-1']={
            glitch={
                length=50,
                bpm=113,
                ['bpm.div']=4,
                dry=100
            },
            delay={
                level=-6,
                fdbk=-18,
                lop=108,
                hip=30,
                ['mod.rate']=.9,
                ['mod.depth']=3
            },
            ['gt-synth']={
                ['pitch-1']=0,
                ['osc-2']=-100,
                waveform=0,
                ['pitch.lfo.rate']=3,
                ['pitch.lfo.cents']=16,
                cutoff=120,
                Q=.8,
                ['cutoff.key']=0,
                glide=0
            },
            oneoffs={
                master=3,
                ['ps-synth-sw']=2
            }
        }
    },
}